# Security Policy

## Supported Versions

| Version | Supported          |
| ------- | ------------------ |
| < 1.0   | :white_check_mark: |

## Reporting a Vulnerability

to report a vulnerability please contact
[carlos.lapao@parallels.com](cjlapao@gmail.com) or
@cjlapao if you can please raise a pr with the fix for approval