title: Golang Common Library
theme: just-the-docs
logo: "/images/logo.png"
url: "http://localhost:4000"
baseurl: ""
search_enabled: true
permalink: pretty
exclude: [
  "node_modules/", 
  "*.gemspec", 
  "*.gem", 
  "Gemfile", 
  "Gemfile.lock", 
  "package.json", 
  "package-lock.json",  
  "script/", "LICENSE.txt", 
  "lib/", 
  "bin/", 
  "README.md", 
  "Rakefile" , 
  "docs/tests/"]
aux_links:
  "On Github":
    - "https://github.com/cjlapao/go-template"
aux_links_new_tab: false
footer_content: "Copyright &copy; Carlos Lapao <a href=\"https://opensource.org/licenses/MIT\">MIT license.</a>"
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
heading_anchors: true
nav_sort: case_sensitive
back_to_top: true
back_to_top_text: "Back to top"
plugins:
  - jekyll-seo-tag
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
